viaa:
    logging:
        level: DEBUG
app:
    self:
        # App name: not needed but to not leave `self` empty
        name: "pg-listener-py"
    pulsar:
        host: !ENV ${PULSAR_HOST}
        port: !ENV ${PULSAR_PORT}
        namespace: !ENV ${PULSAR_NAMESPACE}
        topic: !ENV ${PULSAR_TOPIC}
    db:
        host: !ENV ${DB_HOST}
        port: !ENV ${DB_PORT}
        name: !ENV ${DB_NAME}
        user: !ENV ${DB_USER}
        password: !ENV ${DB_PASSWORD}
        channel: !ENV ${DB_CHANNEL_NAME}
